// Catálogo de distritos hardcodeados
export const DISTRICTS = [
  { id: 1, name: "Ancón" },
  { id: 2, name: "Ate" },
  { id: 3, name: "Barranco" },
  { id: 4, name: "Breña Alta" },
  { id: 5, name: "Chaclacayo" },
  { id: 6, name: "Chorrillos" },
  { id: 7, name: "Comas" },
  { id: 8, name: "Cono Norte" },
  { id: 9, name: "Cono Sur" },
  { id: 10, name: "El Agustino" },
  { id: 11, name: "La Molina" },
  { id: 12, name: "La Punta" },
  { id: 13, name: "La Victoria" },
  { id: 14, name: "Lima" },
  { id: 15, name: "Lince" },
  { id: 16, name: "Los Olivos" },
  { id: 17, name: "Lurín" },
  { id: 18, name: "Magdalena del Mar" },
  { id: 19, name: "Miraflores" },
  { id: 20, name: "Pachacamac" },
  { id: 21, name: "Pucusana" },
  { id: 22, name: "Puente Piedra" },
  { id: 23, name: "Punta Hermosa" },
  { id: 24, name: "Punta Negra" },
  { id: 25, name: "Rímac" },
  { id: 26, name: "San Bartolo" },
  { id: 27, name: "San Isidro" },
  { id: 28, name: "San Juan de Lurigancho" },
  { id: 29, name: "San Juan de Miraflores" },
  { id: 30, name: "San Luis" },
  { id: 31, name: "San Martín de Porres" },
  { id: 32, name: "San Miguel" },
  { id: 33, name: "Santa Anita" },
  { id: 34, name: "Santa María del Mar" },
  { id: 35, name: "Santa Rosa" },
  { id: 36, name: "Santiago de Surco" },
  { id: 37, name: "Surquillo" },
  { id: 38, name: "Villa El Salvador" },
  { id: 39, name: "Villa María del Triunfo" },
];
